services:
  backend:
    image: ghcr.io/aswin-s-thampalakadd/used_car_sale_application/backend:latest
    container_name: used-car-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: used-car-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: used_car
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d used_car"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_production_data:
