const usersTypess = {
  ADMIN: {
    name: "ADMIN",
  },
  CUSTOMER: {
    name: "CUSTOMER",
  },
  DEALER: {
    name: "DEALER",
  },
  OPERATOR: {
    name: "OPERATOR",
  },
};

const dummyUsers = {
  ADMIN: {
    name: "Admin",
    email: "admin@gmail.com",
    phone: "9000000001",
    password: "111111",
  },

  CUSTOMER: {
    name: "Customer",
    email: "customer@gmail.com",
    phone: "9000000002",
    password: "111111",
  },

  DEALER: {
    name: "Dealer",
    email: "dealer@gmail.com",
    phone: "9000000003",
    password: "111111",
  },

  OPERATOR: {
    name: "Operator",
    email: "operator@gmail.com",
    phone: "9000000004",
    password: "111111",
  },
};

const dummyDealer = {
  dealershipName: "Aswin Motors",
  description:
    "Trusted pre-owned car dealership offering quality inspected vehicles.",
  logo: "https://example.com/logos/aswin-motors.png",
  address: "MG Road, Kochi",
  city: "Kochi",
  state: "Kerala",
  country: "India",
  pincode: "682016",
  latitude: "9.931233",
  longitude: "76.267303",
  gstNumber: "32ABCDE1234F1Z5",
  isVerified: true,
};

const carFeatures = [
  "Air Conditioning",
  "Power Steering",
  "Power Windows",
  "Central Locking",
  "Airbags",
  "ABS",
  "Rear Parking Camera",
  "Parking Sensors",
  "Bluetooth",
  "Apple CarPlay",
  "Android Auto",
  "Cruise Control",
  "Sunroof",
  "Alloy Wheels",
  "Keyless Entry",
  "Push Button Start",
];

const dummyCars = [
  {
    make: "Toyota",
    model: "Fortuner",
    variant: "2.8 4x2 AT",
    year: 2021,
    registrationYear: 2021,
    fuelType: "diesel",
    transmission: "automatic",
    kilometersDriven: 42000,
    price: "3450000.00",
    color: "White",
    condition: "excellent",
    description:
      "Well-maintained Toyota Fortuner with automatic transmission and excellent service history.",
    registrationNumber: "KL07AB1234",
    isNegotiable: true,
    status: "active",
    isFeatured: true,
    viewsCount: 125,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Rear Parking Camera",
      "Parking Sensors",
      "Bluetooth",
      "Cruise Control",
      "Alloy Wheels",
      "Keyless Entry",
      "Push Button Start",
    ],
    images: [
      "https://example.com/cars/fortuner-1.jpg",
      "https://example.com/cars/fortuner-2.jpg",
      "https://example.com/cars/fortuner-3.jpg",
    ],
  },

  {
    make: "Hyundai",
    model: "Creta",
    variant: "SX 1.5 Diesel",
    year: 2022,
    registrationYear: 2022,
    fuelType: "diesel",
    transmission: "manual",
    kilometersDriven: 28000,
    price: "1625000.00",
    color: "Black",
    condition: "excellent",
    description:
      "Single-owner Hyundai Creta in excellent condition with low kilometers and complete service history.",
    registrationNumber: "KL01CD5678",
    isNegotiable: true,
    status: "active",
    isFeatured: true,
    viewsCount: 210,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Rear Parking Camera",
      "Bluetooth",
      "Apple CarPlay",
      "Android Auto",
      "Alloy Wheels",
      "Keyless Entry",
    ],
    images: [
      "https://example.com/cars/creta-1.jpg",
      "https://example.com/cars/creta-2.jpg",
      "https://example.com/cars/creta-3.jpg",
    ],
  },

  {
    make: "Honda",
    model: "City",
    variant: "VX CVT",
    year: 2020,
    registrationYear: 2020,
    fuelType: "petrol",
    transmission: "cvt",
    kilometersDriven: 35000,
    price: "1125000.00",
    color: "Silver",
    condition: "good",
    description:
      "Comfortable and reliable Honda City with smooth CVT transmission and excellent interiors.",
    registrationNumber: "KL05EF9012",
    isNegotiable: true,
    status: "active",
    isFeatured: false,
    viewsCount: 98,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Rear Parking Camera",
      "Bluetooth",
      "Apple CarPlay",
      "Android Auto",
      "Cruise Control",
    ],
    images: [
      "https://example.com/cars/city-1.jpg",
      "https://example.com/cars/city-2.jpg",
    ],
  },

  {
    make: "Tata",
    model: "Nexon",
    variant: "XZ Plus",
    year: 2021,
    registrationYear: 2021,
    fuelType: "petrol",
    transmission: "manual",
    kilometersDriven: 31000,
    price: "875000.00",
    color: "Blue",
    condition: "good",
    description:
      "Well-maintained Tata Nexon with good mileage, spacious interiors and strong safety features.",
    registrationNumber: "KL10GH3456",
    isNegotiable: false,
    status: "active",
    isFeatured: false,
    viewsCount: 76,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Rear Parking Camera",
      "Parking Sensors",
      "Bluetooth",
      "Android Auto",
      "Alloy Wheels",
    ],
    images: [
      "https://example.com/cars/nexon-1.jpg",
      "https://example.com/cars/nexon-2.jpg",
    ],
  },

  {
    make: "Maruti Suzuki",
    model: "Baleno",
    variant: "Alpha",
    year: 2019,
    registrationYear: 2019,
    fuelType: "petrol",
    transmission: "manual",
    kilometersDriven: 46000,
    price: "685000.00",
    color: "Red",
    condition: "good",
    description:
      "Economical and well-maintained Maruti Suzuki Baleno suitable for city and highway driving.",
    registrationNumber: "KL12IJ7890",
    isNegotiable: true,
    status: "active",
    isFeatured: false,
    viewsCount: 54,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Bluetooth",
      "Alloy Wheels",
      "Keyless Entry",
    ],
    images: [
      "https://example.com/cars/baleno-1.jpg",
      "https://example.com/cars/baleno-2.jpg",
    ],
  },

  {
    make: "Kia",
    model: "Seltos",
    variant: "HTX 1.5",
    year: 2022,
    registrationYear: 2022,
    fuelType: "petrol",
    transmission: "automatic",
    kilometersDriven: 22000,
    price: "1540000.00",
    color: "Grey",
    condition: "excellent",
    description:
      "Low-mileage Kia Seltos with automatic transmission and premium features.",
    registrationNumber: "KL13KL2468",
    isNegotiable: true,
    status: "active",
    isFeatured: true,
    viewsCount: 185,
    features: [
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Airbags",
      "ABS",
      "Rear Parking Camera",
      "Parking Sensors",
      "Bluetooth",
      "Apple CarPlay",
      "Android Auto",
      "Cruise Control",
      "Alloy Wheels",
      "Keyless Entry",
      "Push Button Start",
    ],
    images: [
      "https://example.com/cars/seltos-1.jpg",
      "https://example.com/cars/seltos-2.jpg",
      "https://example.com/cars/seltos-3.jpg",
    ],
  },
];

module.exports = {
  usersTypess,
  dummyUsers,
  dummyDealer,
  carFeatures,
  dummyCars,
};
